### PR TITLE
Added 4 items from Bio Industries

### PR DESCRIPTION
**Pull request by snouz**
I haven't included more, because in the next upcoming version, most of the rest will become optional / modular.

### CODE REVIEW

**Comment by Wiwiweb** [comment]
Thanks for the pull request!

Note that the presets don't combine, only one is picked. So here, if someone is playing Bio Industries then they would only start with 4 milestones and would basically have to setup the rest.

I'm not familiar with Bio Industries but I imagine it still has the usual science packs and vanilla items? You should copy the Vanilla preset into this preset, and then add the 4 modded items to it :)

I also see in this mod's description that it's meant to be played with Bob's? In that case I would also add a "BI + Bob" preset, where you copy paste the Bob preset then add your 4 new items to it.

**Comment by snouz** [comment]
Seems like I completely misunderstood how this list works...

I thought it was additive, like this
If you have mods A + B + D, you've have items from lists A + B + D, automatically detected.
Instead you need to make a list for every combination of mods?

But now I'm wondering : would my description be something you'd prefer over the current system? And how hard would it be to code?

BTW, The old description about BI is inaccurate : it's compatible with most mods, and soon, extremely modular. I'm currently using it with SE.

**Comment by Wiwiweb** [comment]
Yeah, I underestimated how many big mods can be used with anything. 

I originally figured having set lists for combinations would allow greater control over which milestones and in which order they are listed. Especially since the combination of two mods can sometimes become a 3rd new thing entirely. E.g. Angel's "paper" is a big milestone in B&A, but useless with only Angel's.

I think I want to keep this set preset list, but also add a "preset_addons" list which would just dumbly append milestones to the end of the preset if a mod is detected. That sounds like the best of both worlds.

Shouldn't be too hard, I'll work on that though it won't be done today.

**Comment by snouz** [comment]
One suggestion:
Add a bool to items in the list, so you can remove items from previously declared mods.

Example: 
-base list
-SE list -> includes "space science pack: enabled = false"
-Bob list
-Angel list
-Bob & angel list

An item could be disabled if it appears a second time with "enabled = false"

Also, it'd be useful to take options into consideration.
mod = [bioIndustries] && setting ABC = true
 { list }

This would be a true dynamic list !
But the mod is great already, this is a neat idea and I'm using it in my current game.

**Comment by Wiwiweb** [comment]
Hi again!

I just added the concept of preset addons. It shows like this to the player:
image

Could you please rebase your changes on top of this, and move the milestones you created inside [preset_addons.lua](https://github.com/Wiwiweb/FactorioMilestones/blob/main/scripts/preset_addons.lua)?

**Comment by Wiwiweb** [comment]
I took the liberty to rebase myself manually, but you are still marked a author of the commit. Thanks again for the pull request :)

**Pull request closed without merging**
